In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
iris = datasets.load_iris()
X = iris.data 
y = iris.target 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 100.00%


In [2]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
iris = datasets.load_iris()
X = iris.data 
y = iris.target 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()

nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
cm=confusion_matrix(y_test,y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
print(cm)

Accuracy: 100.00%
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
data = load_iris()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of Naive Bayes: {accuracy:.2f}")
print("\nEnter the flower measurements:")
sepal_length = float(input("Sepal length (cm): "))
sepal_width = float(input("Sepal width (cm): "))
petal_length = float(input("Petal length (cm): "))
petal_width = float(input("Petal width (cm): "))
newrow = np.array([[sepal_length,sepal_width,petal_length,petal_width]])
prediction = nb_classifier.predict(newrow)
species = data.target_names[prediction[0]]
print(f"\nPredicted Iris species: {species}")


Accuracy of Naive Bayes: 1.00

Enter the flower measurements:


Sepal length (cm):  4
Sepal width (cm):  2
Petal length (cm):  5
Petal width (cm):  2



Predicted Iris species: virginica


In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
df = pd.read_csv("/home/user/Downloads/dat (1).csv")
print(df.head(10))
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
print(f"Accuracy of Naive Bayes: {accuracy:.2f}")
print("Confusion Matrix:")
print(cm)
print("\nEnter the values:")
study_hours = float(input("Study hours: "))
attendance = float(input("Attendance percentage: "))
assignments = int(input("Assignments completed: "))
sleep_hours = float(input("Sleep hours: "))
newrow = np.array([[study_hours, attendance, assignments, sleep_hours]])
prediction = nb_classifier.predict(newrow)
print("\nPredicted result:", prediction[0])

   Study_Hours  Attendance  Assignments_Completed  Sleep_Hours Result
0            1          55                      2            4   Fail
1            2          60                      3            5   Fail
2            2          65                      4            5   Fail
3            3          68                      4            6   Fail
4            3          70                      5            5   Fail
5            4          72                      5            6   Fail
6            4          75                      6            6   Pass
7            5          78                      7            7   Pass
8            5          80                      7            6   Pass
9            6          82                      8            7   Pass
Accuracy of Naive Bayes: 1.00
Confusion Matrix:
[[4 0]
 [0 7]]

Enter the values:


Study hours:  3
Attendance percentage:  56
Assignments completed:  5
Sleep hours:  5



Predicted result: Fail
